### PR TITLE
Expanding testing to semiology_dictionary and dummy data to ensure robustness

### PR DESCRIPTION
**Pull request by thenineteen**
testing for existing and non existing semiology and semiology_dictionary use at the same time

also related to:
fixtures #74 
Parenthesis #95
Localisation columns #71

### CODE REVIEW

**Comment by thenineteen** [comment]
the idea is to increase test coverage so that I can fix the regex and attend to the other 2 reamaining bugs. Fixing regexes espeecially, may not fail tests but change the behaviour.

Similarly to allow us to improve performance with profiling

**Comment by thenineteen** [comment]
so far the above combinations of testing, debugging the tests with breakpoints and new data, have resulted in the in following insights and changes:

- QUERY_SEMIOLOGY.py being confirmed as behaving correctly even when there are parentheses. 
- important updates not specific to this branch for the localisation columns in group_columns. Three very important updates correcting previously unknown erroneous behaviour (but suspected in multiple issues incl #71 )  (3684468, 6ce476f, 1bd7bef)
- MEGA_ANALYSIS logging debug corrected for sEEG_ES term

**Comment by thenineteen** [comment]
@fepegar can you make 

semiology.py to have more flexibile semiology_dictionary and DataFrame references? e.g. move as a method of Class Semiology?

I need to cover more test cases for top level function calls to ensure there is consistent behaviour of the code across the levels
# Read YAML
all_semiology_terms = get_all_semiology_terms()

**Comment by thenineteen** [comment]
as per discussion on #82 I've added @fepegar 's `test_get_lobes` and this now works as intended.

@fepegar please confirm you're happy with this now?

**Comment by fepegar** [comment]
It's hard to know what's going on in this PR with so many commits. You could maybe squash your commits and force-push: https://github.com/Slicer/Slicer/pull/4789#issuecomment-606791186

It will be easier to see what's changed.

**Comment by thenineteen** [comment]
> It's hard to know what's going on in this PR with so many commits. You could maybe squash your commits and force-push: [Slicer/Slicer#4789 (comment)](https://github.com/Slicer/Slicer/pull/4789#issuecomment-606791186)
> 
> It will be easier to see what's changed.

I wouldl pull the branch, then compare with master in your editor - vs code would then show you all the changes at the same time?

**Comment by fepegar** [comment]
I shouldn't need to fetch a branch just to see the changes.

**Comment by thenineteen** [comment]
I'm sorry I'm too busy to spend time figuring out how to do this when it takes 2 secs to fetch a branch

**Pull request merged**
