### PR TITLE
Readme picture

### PR DESCRIPTION
**Pull request by thenineteen**
@fepegar upload your version of all_automatisms (as colour bar is working) onto resources? otherwise good enough for a readme pic

### CODE REVIEW

**Comment by fepegar** [comment]
Something like this?

Screenshot 2020-04-09 23 27 29

**Comment by fepegar** [comment]
Something like this?

Screenshot 2020-04-09 23 28 44

**Comment by thenineteen** [comment]
yes - I'd keep the 3D view without removing a hemisphere

**Comment by fepegar** [comment]
Screenshot 2020-04-10 11 46 12

**Pull request merged**
