### PR TITLE
ignore Warning: This pattern has match groups.

### PR DESCRIPTION
**Pull request by thenineteen**

### CODE REVIEW

**Comment by fepegar** [comment]
Ignoring a warning is not a solution, it's a patch. Warnings are snowballs that end up being bugs, especially if they are ignored.

**Comment by thenineteen** [comment]
not regular expression ones. 

[see here](https://stackoverflow.com/questions/39901550/python-userwarning-this-pattern-has-match-groups-to-actually-get-the-groups)

**Comment by fepegar** [comment]
That guy is saying "Fix it like this. Alternatively, you can ignore it". There are multiple solutions proposed in that question, like [this one](https://stackoverflow.com/a/59367976/3956024).

**Comment by thenineteen** [comment]
can't implement changes to regex without first having fixtures: issue #74

**Comment by fepegar** [comment]
Closing in favour of #79.

**Pull request closed without merging**
