### PR TITLE
fix build errors

### PR DESCRIPTION
**Pull request by thenineteen**

### CODE REVIEW

**Comment by fepegar** [comment]
Again, I recommend you create a different branch and PR for each fix.

**Comment by thenineteen** [comment]
can you have a look at semiology.py > get_num_patients_dict()

if query_lat is None, then a series of other functions need to be called which haven't been called yet in the order I've inserted.

**Comment by fepegar** [comment]
Once again, this is too many changes. Also, `try` blocks with bare `except`s are almost always a bad idea.

**Comment by thenineteen** [comment]
yes i'm aware, just trying to fix this one then will go to one pull per issue/build fail. also aware of bare except problemo but the code isn't factored either, trying to make it work first then we can worry about refactoring and bare except?

**Comment by thenineteen** [comment]
you see you've changed a few little things or i have and so far we haven't had to use the separate modules outside of QUERY_LATERALISATION so haven't noticed that e.g. calls to big_map() are broken... next fix of this coming up

**Comment by fepegar** [comment]
I can't help with this many changes. Each issue should be solved separately.

**Comment by thenineteen** [comment]
> I can't help with this many changes. Each issue should be solved separately.

this is just one change in pivot_result_to_one_map?

**Comment by thenineteen** [comment]
plus if you look at the revision changes of the comnits, some are mirco and others are already superceded (or rather duplicated) by the commits you've already made to master and were remerged back here.

**Comment by fepegar** [comment]
Result of `QUERY_SEMIOLOGY` is an empty data frame for 'Figure of 4'.

**Pull request merged**
